// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(RequestContext))]
    partial class RequestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("WebAPI.Models.Request", b =>
                {
                    b.Property<int>("no")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("date")
                        .HasColumnType("BIGINT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("fio")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("firm")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("no");

                    b.ToTable("RequestDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
